services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"  # Different port for staging
    environment:
      - REACT_APP_API_URL=http://localhost:8081
      - NODE_ENV=staging
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
    ports:
      - "8081:8080"  # Different port for staging
    environment:
      - MONGO_URI=mongodb://mongo:27017/cloudtaskpro_staging
      - JWT_SECRET_KEY=staging-secret-key
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - "27018:27017"  # Different port for staging
    volumes:
      - mongo_staging_data:/data/db

volumes:
  mongo_staging_data: 