#!/bin/bash

echo "🔧 Jenkins Configuration Helper"
echo "================================"
echo ""
echo "After Jenkins starts, you'll need to:"
echo ""
echo "1. 📋 Get the initial admin password:"
echo "   docker exec jenkins-cicd cat /var/jenkins_home/secrets/initialAdminPassword"
echo ""
echo "2. 🌐 Open Jenkins in browser:"
echo "   http://localhost:8085"
echo ""
echo "3. 📦 Install suggested plugins"
echo ""
echo "4. 👤 Create admin user"
echo ""
echo "5. 🔗 Create a new Pipeline job:"
echo "   - New Item > Pipeline"
echo "   - Name: CloudTaskPro-CI-CD"
echo "   - Pipeline > Definition: Pipeline script from SCM"
echo "   - SCM: Git"
echo "   - Repository URL: /var/jenkins_home/workspace/cloudtaskpro"
echo "   - Script Path: Jenkinsfile"
echo ""
echo "6. 🚀 Run the pipeline!"
