services:
  jenkins:
    build: .
    container_name: jenkins-cicd
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/var/jenkins_home/workspace/cloudtaskpro
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
